### ISSUE TITLE
How do I exactly build THIS version of Dopamine? (Version 3)

### ISSUE THREAD

**Issue by Socketlike** [digimezzo/dopamine#22]
I have tried using npm to build but I can't. Can you help me how to build Dopamine 3? Tysm.

**Comment by dragonBall561** [comment]
If you want to build, see readme.md.

1. First Install NodeJS and NPM.
    a. Linux Debian/Debian-Based:
        
       curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
       sudo apt install -y nodejs

    b. Windows:
        Get the .exe from [NodeJS Downoads](https://nodejs.org/en/download/current/)

    c. Mac:
        Get the PKG installer from [NodeJS Downloads](https://nodejs.org/en/download/current/) 

    d. Or use Homebrew For Mac:
        Install [XCode from App Store](http://itunes.apple.com/us/app/xcode/id497799835?ls=1&mt=12)
        Open Terminal and Run:
                
       ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
       brew update
       brew install node
                

If you are on Linux, Clone Dopamine with Git Clone (See readme) or with windows and mac, download and extract the zip.
Then go into the Dopamine folder and open a Terminal/CMD Prompt window there.
Now run:

     npm install
     npm run rebuild-sqlite
     npm start

**Comment by dragonBall561** [comment]
For me, Building from Linux Gets me a .AppImage, a .deb, and a .snap.

**Comment by SkilledTheGamer** [comment]
Thanks! I'll definitely try this when I get back home.

**Comment by Cyberdroid1** [comment]
Trying to run the command ` npm run rebuild-sqlite ` fails on my Win10 PC.

![image](https://user-images.githubusercontent.com/51435948/97785147-467e7080-1bc9-11eb-9876-873ebf10630d.png)

Please help me.

**Comment by Cyberdroid1** [comment]
Trying to run ` npm start ` gives more error.

![image](https://user-images.githubusercontent.com/51435948/97785301-39ae4c80-1bca-11eb-9f01-4941fa8fa1b0.png)

Is it because I ran ` npm audit fix --force ` ?

**Comment by digimezzo** [comment]
@Cyberdroid1 Please try without running `npm audit fix --force`
This command is dangerous, because it updates dependencies of dependencies. This usually causes a massive amount of problems.

**Comment by Cyberdroid1** [comment]
But, about the command ` npm run rebuild-sqlite ` always fails

**Comment by digimezzo** [comment]
Have you installed the Windows build tools?

**Comment by Cyberdroid1** [comment]
Yes. See the image above I have attached.

**Comment by Cyberdroid1** [comment]
I started again from scratch.

![image](https://user-images.githubusercontent.com/51435948/97798323-1d062900-1c4b-11eb-889c-b2931f09deb4.png)

Running ` npm install ` keeps giving vulnerability errors.

**Comment by Cyberdroid1** [comment]
After running ` npm audit fix ` , I still get some vulnerability errors. How do I fix that?

**Comment by digimezzo** [comment]
Please do'nt try to fix these and read this pinned issue: https://github.com/digimezzo/dopamine/issues/68
The pinned issue contains an article that might clear things up: https://www.voitanos.io/blog/don-t-be-alarmed-by-vulnerabilities-after-running-npm-install/

**Comment by Cyberdroid1** [comment]
Ok, so I tried again, without fixing anything. It gets rebuild. And it opens on ` npm start `. When the window opens, it is all blank. Nothing in it. The Inspect menu on the right says something that sharp module is causing problem/not found. How do I fix that?

**Comment by digimezzo** [comment]
Which version of sharp is listed when you perform this command?

`npm list sharp`

**Comment by Cyberdroid1** [comment]
0.25.4

![image](https://user-images.githubusercontent.com/51435948/97801717-a70ebb80-1c64-11eb-8ac4-cb274aa47a03.png)

**Comment by digimezzo** [comment]
It seems that the rebuild-sqlite command also rebuilt sharp. This broke the sharp module. I don't know why it breaks it though. Using native modules in Electron is quite complicated. However, it was never my intent to rebuild sharp with the rebuild-sqlite command, so I've now updated that command in package.json, so that it only builds better-sqlite3. You should be able to fix your sharp issue by doing this:

- Delete the **Sharp** directory from node_modules
- Run **npm install** to reinstall sharp
- Run **npm start** again to start the application

Next time you run npm run rebuild-sqlite should not break sharp again. I'll try to further understand why rebuilding sharp breaks it though.

**Comment by Cyberdroid1** [comment]
Why does the command ` npm run rebuild-sqlite ` looks for a specific file location? It should run in its present repository, right? I keep getting error for invalid file location. Though I can change the command for the same, but still, can this not be fixed?

![image](https://user-images.githubusercontent.com/51435948/97808067-822d3f00-1c8a-11eb-8c15-c2d9279b5da5.png)

**Comment by Cyberdroid1** [comment]
Thanks, the app builds correctly now. The other problem that I face is this --

![image](https://user-images.githubusercontent.com/51435948/97808173-64140e80-1c8b-11eb-9e72-740e1369494c.png)

The library stays blank. The Manage collections button does not do anything. Please help me with this.

**Comment by digimezzo** [comment]
I don't yet know why the rebuild sqlite command it failing. I'll look into it. As for the collection remaining empty, and some screens not working: that is normal 🙂. Dopamine 3 is in early development and does nothing yet. Well, the settings screens are operational, and audio files are indeed and album art is downloaded from the internet. But the player does not display the collection yet, and cannot play music. That is will gradually be added in the next few weeks.

**Comment by TragicLifeHu** [comment]
It's not possible to build version 3 following the instruction above on Windows now. (And on my openSUSE Leap 15.2 I didn't success, too)

Microsoft had shut down everything about Visual Studio 2015, including Microsoft Build Tools 2015. Installing windows-build-tools vs2015 will result in vs2017 to be installed.
More info here: https://github.com/felixrieseberg/windows-build-tools/issues/249

As for @Cyberdroid1 's issue mentioned above, I found this: https://www.programmersought.com/article/19371828050/
![image](https://user-images.githubusercontent.com/16817202/123822716-1e4d3a00-d92f-11eb-90e7-53a87983968d.png)

I don't know many about Node.js, so I just try building for fun. Sorry for troubling

**Comment by digimezzo** [comment]
@TragicLifeHu I'll update the build instructions this week.

**Comment by digimezzo** [comment]
@TragicLifeHu With some delay, I've updated the build instructions. I tested the instructions on 2 clean Windows 10 PC's. The trick is to install Node.js including the Tools for Native Modules.

**Comment by thataboy** [comment]
Hello

I'm trying to build dopamine 3 for Apple Silicon on an M1 Mac mini. (The release package is for Intel Mac. It works but is not ideal.) During `npm install` I get

```
npm ERR! code 1
npm ERR! path /Users/me/dev/dopamine/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.6.2 build-release
npm ERR! > node-gyp rebuild --release
npm ERR!
npm ERR!   TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
npm ERR!   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
npm ERR!   LIBTOOL-STATIC Release/sqlite3.a
npm ERR! rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.16.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@18.16.0 | darwin | arm64
...
``` 

I installed node.js 18.16 LTS using the arm64 pkg installer for MacOS. During the install, there was no option to install Tools for Native Modules, only node.js and npm (I clicked Customize...). Is that why better-sqlite3 and others are missing?

Is there some way to install the tools separately? I googled but could not find it. 

thanks in advance

**Comment by overestimate** [comment]
@thataboy looks like it's attempting to manually build dependencies instead. Are you sure it's not going to work?

**Comment by thataboy** [comment]
> @thataboy looks like it's attempting to manually build dependencies instead. Are you sure it's not going to work?

Thank you, but it ended with all errors, so alas no. Here's the full output. Maybe you can spot something.

```
npm install
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated core-js@2.6.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@3.16.0: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/me/dev/dopamine/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.6.2 build-release
npm ERR! > node-gyp rebuild --release
npm ERR!
npm ERR!   TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
npm ERR!   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
npm ERR!   LIBTOOL-STATIC Release/sqlite3.a
npm ERR! rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.16.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@18.16.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.10 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
npm ERR! (node:20762) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/me/dev/dopamine/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/me/dev/dopamine/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/me/dev/dopamine/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/me/Library/Caches/node-gyp/18.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/me/Library/Caches/node-gyp/18.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/me/dev/dopamine/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/me/Library/Caches/node-gyp/18.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/me/dev/dopamine/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! env: python: No such file or directory
npm ERR! make: *** [Release/sqlite3.a] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/me/dev/dopamine/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 22.4.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/me/dev/dopamine/node_modules/.bin/node-gyp" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/me/dev/dopamine/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/me/.npm/_logs/2023-05-01T00_47_28_850Z-debug-0.log
```

**Comment by overestimate** [comment]
> `npm ERR! env: python: No such file or directory`
Install [brew](https://brew.sh/), run `brew install python`, then try again.

**Comment by thataboy** [comment]
@overestimate I do have python installed. See

```
npm ERR! gyp info find Python using Python version 3.10.10 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
```

**Comment by digimezzo** [comment]
Node 18 is not supported yet. I need to have a look at that. Until then, only the previous LTS of Node is supported (v16.20.0). I'm planning to fix this for the next preview.

**Comment by thataboy** [comment]
@digimezzo thank you for replying. I nuked all the nodejs stuff I could find and installed nodejs 16.20 LTS. `rm -rf dopamine` and re cloned from git. I still got exact same errors on `npm install`

```
npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated electron-rebuild@2.3.2: Please use @electron/rebuild moving forward.  There is no API change, just a package name change
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated core-js@2.6.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@3.16.0: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/me/dev/dopamine/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c -- prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.6.2 build-release
npm ERR! > node-gyp rebuild --release
npm ERR!
npm ERR!   TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
npm ERR!   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
npm ERR!   LIBTOOL-STATIC Release/sqlite3.a
npm ERR! rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! prebuild-install warn install No prebuilt binaries found (target=16.20.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.20.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.10 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
npm ERR! (node:69108) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/me/dev/dopamine/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/me/dev/dopamine/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/me/dev/dopamine/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/me/Library/Caches/node-gyp/16.20.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/me/Library/Caches/node-gyp/16.20.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/me/dev/dopamine/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/me/Library/Caches/node-gyp/16.20.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/me/dev/dopamine/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! env: python: No such file or directory
npm ERR! make: *** [Release/sqlite3.a] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/me/dev/dopamine/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.4.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/me/dev/dopamine/node_modules/.bin/node-gyp" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/me/dev/dopamine/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v16.20.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2023-05-08T15_25_40_600Z-debug-0.log
```

**Comment by digimezzo** [comment]
Better-sqlite3 again. It's a pain to build when there are no prebuilt binaries available. I'd prefer not to use it anymore, but couldn't find a viable alternative. I'll look into it.

This seems to be related https://github.com/bluesky-social/atproto/issues/962.

**Comment by digimezzo** [comment]
@thataboy I saw that version 7.6.2 of better-sqlite3 has no prebuilt binaries for darwin-arm64. So I've updated better-sqlite3 to version 8.3.0 which does have prebuilt binaries for darwin-arm64. Crossing fingers that it works. Could you pull from this repo again to get the updated package.json and try npm install again?

**Comment by thataboy** [comment]
@digimezzo Thank you for your patience. It still fails with no prebuilt binaries. I checked package.json after pulling from repo and it does have dependencies > better-sqlite3 set to 8.3.0

```
npm ERR! code 1
npm ERR! path /Users/me/dev/dopamine/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c -- prebuild-install || node-gyp rebuild --release
npm ERR! TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
npm ERR!   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
npm ERR!   LIBTOOL-STATIC Release/sqlite3.a
npm ERR! rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! prebuild-install warn install No prebuilt binaries found (target=16.20.0 runtime=node arch=arm64 libc= platform=darwin)
```

how do you tell which version of a package has prebuilt binaries for which node version and arch?

**Comment by digimezzo** [comment]
@thataboy You're welcome. As for the prebuilt binaries, I am not sure I'm checking the correct place (it's the only one I found), but I look at the assets in the releases: https://github.com/WiseLibs/better-sqlite3/releases/tag/v8.3.0

For v8.0.0 and above I saw that there are Darwin arm64 binaries. However I don't understand this fully, as the electron version is so old in the filenames of the binaries.

**Comment by digimezzo** [comment]
@sdwav The missing features are just not implemented yet. Version 3 was a complete rewrite (there was no other way to go cross platform) and I'm adding the features gradually. This is the roadmap: https://github.com/digimezzo/dopamine/milestones

**Comment by sdwav** [comment]
> @sdwav The missing features are just not implemented yet. Version 3 was a complete rewrite (there was no other way to go cross platform) and I'm adding the features gradually. This is the roadmap: https://github.com/digimezzo/dopamine/milestones

Thanks for the reply i thought i was missing something. Another question though does downloading the exe vs all the build  prerequisites and stuff that you manually "build"? I'm also having a problem where it wont play any alac files if thats not supported thats cool i just couldnt solve the problem.

**Comment by digimezzo** [comment]
You only need the exe to install it. The build prerequisites are for building from source. You should not have to do that. The latest preview has all the features that are available. Alac is not supported yet.
