### ISSUE TITLE
[BUG] Error when running `npm install` and when running `npm run rebuild-sqlite`

### ISSUE THREAD

**Issue by dragonBall561** [digimezzo/dopamine#49]
When `better-sqlite` is being built, I get this error message

```
  • electron-builder  version=22.5.1
  • loaded configuration  file=/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/electron-builder.json
  • rebuilding native dependencies  dependencies=better-sqlite3@7.1.0 platform=linux arch=x64
  • install prebuilt binary  name=better-sqlite3 version=7.1.0 platform=linux arch=x64
  • build native dependency from sources  name=better-sqlite3
                                          version=7.1.0
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.5
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /home/--my-username--/.npm/_prebuilds/6fca5e-better-sqlite3-v7.1.0-electron-v69-linux-x64.tar.gz
    prebuild-install http request GET https://github.com/JoshuaWise/better-sqlite3/releases/download/v7.1.0/better-sqlite3-v7.1.0-electron-v69-linux-x64.tar.gz
    prebuild-install http 404 https://github.com/JoshuaWise/better-sqlite3/releases/download/v7.1.0/better-sqlite3-v7.1.0-electron-v69-linux-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=4.2.12 runtime=electron arch=x64 libc= platform=linux)
    
  ⨯ cannot execute  cause=exit status 1
                    out=
    > better-sqlite3@7.1.0 install /home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3
    > prebuild-install || npm run build-release
    
    
    > better-sqlite3@7.1.0 build-release /home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3
    > node-gyp rebuild --release
    
    make: Entering directory '/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3/build'
      TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
      ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
      TOUCH Release/obj.target/deps/locate_sqlite3.stamp
      CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
      AR(target) Release/obj.target/deps/sqlite3.a
      COPY Release/sqlite3.a
      CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
    rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
    make: Leaving directory '/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3/build'
    
                    errorOut=prebuild-install WARN install No prebuilt binaries found (target=4.2.12 runtime=electron arch=x64 libc= platform=linux)
    make: g++: Command not found
    make: *** [better_sqlite3.target.mk:113: Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 127
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    gyp ERR! System Linux 5.4.0-42-generic
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd /home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3
    gyp ERR! node -v v12.18.2
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok 
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! better-sqlite3@7.1.0 build-release: `node-gyp rebuild --release`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the better-sqlite3@7.1.0 build-release script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/--my-username--/.npm/_logs/2020-07-22T20_27_18_961Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! better-sqlite3@7.1.0 install: `prebuild-install || npm run build-release`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the better-sqlite3@7.1.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/--my-username--/.npm/_logs/2020-07-22T20_27_19_062Z-debug.log
    
                    command=/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js rebuild better-sqlite3@7.1.0
                    workingDir=
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Dopamine@3.0.0-preview.1 postinstall: `npm run postinstall:electron && electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Dopamine@3.0.0-preview.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/--my-username--/.npm/_logs/2020-07-22T20_27_19_341Z-debug.log
```

I will attach the NPM log.
[NPM_ERROR_LOG.log](https://github.com/digimezzo/dopamine/files/4962552/NPM_ERROR_LOG.log)

This is the output that I get when running `npm run rebuild-sqlite`:

```
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
make: Entering directory '/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3/build'
  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
make: g++: Command not found
make: *** [better_sqlite3.target.mk:113: Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 127
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
make: Leaving directory '/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/bin/node" "/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/.bin/node-gyp" "rebuild" "--target=4.2.12" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1

Error: make: Entering directory '/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3/build'
  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
make: g++: Command not found
make: *** [better_sqlite3.target.mk:113: Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 127
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
make: Leaving directory '/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/bin/node" "/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/.bin/node-gyp" "rebuild" "--target=4.2.12" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/better-sqlite3
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/a--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/--my-username--/Apps/Dopamine-Preview-1/dopamine/node_modules/rxjs/internal/Subscriber.js:143:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! Dopamine@3.0.0-preview.1 rebuild-sqlite: `electron-rebuild better-sqlite3`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the Dopamine@3.0.0-preview.1 rebuild-sqlite script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/--my-username--/.npm/_logs/2020-07-22T20_28_49_043Z-debug.log
```

And the log for that one too:
[NPM_ERROR_LOG_2.log](https://github.com/digimezzo/dopamine/files/4962561/NPM_ERROR_LOG_2.log)

**Comment by digimezzo** [comment]
@dragonBall561 Which OS are you using? Some development tools seem to be missing. This post might help: https://unix.stackexchange.com/questions/140350/linux-g-command-not-found/470332

**Comment by dragonBall561** [comment]
Linux Mint 20 (Ubuntu 20.04)

**Comment by dragonBall561** [comment]
I already have the build-essental package

**Comment by dragonBall561** [comment]
I uninstalled and reinstalled the build-essential package and it worked!
