### ISSUE TITLE
v3.0.0-preview.28 Updating covers makes the application crash after indexing songs

### ISSUE THREAD

**Issue by vepain** [digimezzo/dopamine#633]
Updating covers makes the application crash after indexing songs.

I have already remarked this behavior in some previous versions.

**Dopamine version:** v3.0.0-preview.28
**OS:** Ubuntu 22.04

**Comment by digimezzo** [comment]
@vepain Could you attach your log file? I'm not seeing this behavior here and would like to see why it crashes on your PC.

**Comment by vepain** [comment]
@digimezzo Thank you for your very fast answer.
Where can I find the logs?

I did a fresh install and it crashes the same way, after reindexing my library and during the cover updating process.
Note that I have some large cover files.

**Comment by digimezzo** [comment]
@vepain You're welcome. You'll find the logs in ~/.config/dopamine/logs. There should be a file dopamine.log

**Comment by vepain** [comment]
```log
[2024-07-27 18:59:24.668] [info]  [Main] [Main] +++ Starting +++
[2024-07-27 18:59:25.268] [info]  [AppComponent] [ngOnInit] +++ Started Dopamine 3.0.0-preview.28 +++
[2024-07-27 18:59:25.298] [info]  [AppearanceService] [applyTheme] Applied theme name=Beats' and theme classes='default-theme-dark'
[2024-07-27 18:59:25.314] [info]  [DatabaseMigrator] [migrateAsync] The database is up to date. No migrations to perform.
[2024-07-27 18:59:25.317] [info]  [FileService] [hasPlayableFilesAsParameters] Found parameters: /opt/Dopamine/dopamine
[2024-07-27 18:59:27.335] [info]  [IndexingService] [indexCollection] Indexing collection.
[2024-07-27 18:59:27.337] [info]  [UpdateService] [checkForUpdatesAsync] Checking for updates
[2024-07-27 18:59:27.544] [info]  [Indexer] [indexCollectionIfOutdatedAsync] Indexing collection.
[2024-07-27 18:59:27.743] [info]  [UpdateService] [checkForUpdatesAsync] Current=3.0.0-preview.28, Latest=3.0.0-preview.28
[2024-07-27 18:59:27.744] [info]  [UpdateService] [checkForUpdatesAsync] Latest (3.0.0-preview.28) <= Current (3.0.0-preview.28). Nothing to do.
[2024-07-27 18:59:29.756] [info]  [CollectionChecker] [isCollectionOutdatedAsync] Collection is outdated: tracksNeedIndexing=false, numberOfTracksHasChanged=false, lastDateModifiedHasChanged=true
[2024-07-27 18:59:29.756] [info]  [Indexer] [indexCollectionIfOutdatedAsync] Collection is outdated.
[2024-07-27 18:59:29.756] [info]  [TrackIndexer] [indexTracksAsync] +++ STARTED INDEXING TRACKS +++
[2024-07-27 18:59:29.758] [info]  [TrackRemover] [removeTracksThatDoNoNotBelongToFoldersAsync] There are no tracks to remove. Time required: 1 ms
[2024-07-27 18:59:29.901] [info]  [TrackRemover] [removeTracksThatAreNotFoundOnDiskAsync] Found 11333 tracks.
[2024-07-27 18:59:30.379] [info]  [TrackRemover] [removeTracksThatAreNotFoundOnDiskAsync] Removed 10 tracks. Time required: 621 ms
[2024-07-27 18:59:30.388] [info]  [TrackRemover] [removeFolderTracksForInexistingTracksAsync] Found 10 folder tracks to remove.
[2024-07-27 18:59:30.405] [info]  [TrackRemover] [removeFolderTracksForInexistingTracksAsync] Removed 10 folder tracks. Time required: 25 ms
[2024-07-27 18:59:31.440] [info]  [TrackUpdater] [updateTracksThatAreOutOfDateAsync] Updated tracks: 18. Time required: 1034 ms
[2024-07-27 18:59:33.880] [info]  [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 2 tracks
[2024-07-27 18:59:33.892] [info]  [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 4 tracks
[2024-07-27 18:59:33.904] [info]  [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 6 tracks
[2024-07-27 18:59:33.918] [info]  [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 8 tracks
[2024-07-27 18:59:33.930] [info]  [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 10 tracks
[2024-07-27 18:59:33.930] [info]  [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Added tracks: 10. Time required: 2490 ms
[2024-07-27 18:59:33.931] [info]  [TrackIndexer] [indexTracksAsync] +++ FINISHED INDEXING TRACKS (Time required: 4174 ms) +++
[2024-07-27 18:59:33.931] [info]  [AlbumArtworkIndexer] [indexAlbumArtworkAsync] +++ STARTED INDEXING ALBUM ARTWORK +++
[2024-07-27 18:59:33.939] [info]  [AlbumArtworkRemover] [removeAlbumArtworkThatHasNoTrackAsync] There is no album artwork to remove. Time required: 8 ms.
[2024-07-27 18:59:33.949] [info]  [AlbumArtworkRemover] [removeAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] There is no album artwork to remove. Time required: 10 ms.
[2024-07-27 18:59:33.950] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Adding album artwork for albumKeyIndex: ''
[2024-07-27 18:59:33.970] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Found 527 album data that needs indexing
[2024-07-27 18:59:33.980] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 1 album artwork
[2024-07-27 18:59:38.232] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 51 album artwork
[2024-07-27 18:59:43.549] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 103 album artwork
```

**Comment by digimezzo** [comment]
@vepain hmm, no errors. What do you see when the crash occurs?

**Comment by vepain** [comment]
@digimezzo Nothing, the app just closes

**Comment by vepain** [comment]
@digimezzo If a redo the operation I get now one error concerning unsupported file format in caches:

```log
[2024-07-27 20:37:18.544] [info]  [Main] [Main] +++ Starting +++
[2024-07-27 20:37:19.146] [info]  [AppComponent] [ngOnInit] +++ Started Dopamine 3.0.0-preview.28 +++
[2024-07-27 20:37:19.178] [info]  [AppearanceService] [applyTheme] Applied theme name=Beats' and theme classes='default-theme-dark'
[2024-07-27 20:37:19.194] [info]  [DatabaseMigrator] [migrateAsync] The database is up to date. No migrations to perform.
[2024-07-27 20:37:19.198] [info]  [FileService] [hasPlayableFilesAsParameters] Found parameters: /opt/Dopamine/dopamine
[2024-07-27 20:37:21.216] [info]  [IndexingService] [indexCollection] Indexing collection.
[2024-07-27 20:37:21.219] [info]  [UpdateService] [checkForUpdatesAsync] Checking for updates
[2024-07-27 20:37:21.407] [info]  [Indexer] [indexCollectionIfOutdatedAsync] Indexing collection.
[2024-07-27 20:37:21.800] [info]  [UpdateService] [checkForUpdatesAsync] Current=3.0.0-preview.28, Latest=3.0.0-preview.28
[2024-07-27 20:37:21.801] [info]  [UpdateService] [checkForUpdatesAsync] Latest (3.0.0-preview.28) <= Current (3.0.0-preview.28). Nothing to do.
[2024-07-27 20:37:51.897] [info]  [IndexingService] [indexAlbumArtworkOnlyAsync] Already indexing.
[2024-07-27 20:37:59.219] [info]  [CollectionChecker] [isCollectionOutdatedAsync] Collection is outdated: tracksNeedIndexing=false, numberOfTracksHasChanged=true, lastDateModifiedHasChanged=false
[2024-07-27 20:37:59.220] [info]  [Indexer] [indexCollectionIfOutdatedAsync] Collection is outdated.
[2024-07-27 20:37:59.220] [info]  [TrackIndexer] [indexTracksAsync] +++ STARTED INDEXING TRACKS +++
[2024-07-27 20:37:59.222] [info]  [TrackRemover] [removeTracksThatDoNoNotBelongToFoldersAsync] There are no tracks to remove. Time required: 1 ms
[2024-07-27 20:37:59.374] [info]  [TrackRemover] [removeTracksThatAreNotFoundOnDiskAsync] Found 11333 tracks.
[2024-07-27 20:37:59.841] [info]  [TrackRemover] [removeTracksThatAreNotFoundOnDiskAsync] Removed 18 tracks. Time required: 618 ms
[2024-07-27 20:37:59.848] [info]  [TrackRemover] [removeFolderTracksForInexistingTracksAsync] Found 18 folder tracks to remove.
[2024-07-27 20:37:59.859] [info]  [TrackRemover] [removeFolderTracksForInexistingTracksAsync] Removed 18 folder tracks. Time required: 18 ms
[2024-07-27 20:38:00.802] [info]  [TrackUpdater] [updateTracksThatAreOutOfDateAsync] Updated tracks: 0. Time required: 943 ms
[2024-07-27 20:38:03.401] [info]  [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Added tracks: 0. Time required: 2598 ms
[2024-07-27 20:38:03.401] [info]  [TrackIndexer] [indexTracksAsync] +++ FINISHED INDEXING TRACKS (Time required: 4181 ms) +++
[2024-07-27 20:38:03.402] [info]  [AlbumArtworkIndexer] [indexAlbumArtworkAsync] +++ STARTED INDEXING ALBUM ARTWORK +++
[2024-07-27 20:38:03.411] [info]  [AlbumArtworkRemover] [removeAlbumArtworkThatHasNoTrackAsync] There is no album artwork to remove. Time required: 9 ms.
[2024-07-27 20:38:03.422] [info]  [AlbumArtworkRemover] [removeAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] There is no album artwork to remove. Time required: 10 ms.
[2024-07-27 20:38:03.422] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Adding album artwork for albumKeyIndex: ''
[2024-07-27 20:38:03.441] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Found 349 album data that needs indexing
[2024-07-27 20:38:03.551] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 1 album artwork
[2024-07-27 20:38:03.801] [error] [AlbumArtworkCache] [addArtworkDataToCacheAsync]  Could not add artwork data to cache. Error: Input buffer contains unsupported image format
[2024-07-27 20:38:07.081] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 34 album artwork
[2024-07-27 20:38:11.422] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 69 album artwork
[2024-07-27 20:38:14.923] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 103 album artwork
[2024-07-27 20:38:18.624] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 138 album artwork
[2024-07-27 20:38:22.310] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 173 album artwork
[2024-07-27 20:38:26.356] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 208 album artwork
[2024-07-27 20:38:30.790] [info]  [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 243 album artwork
```

**Comment by digimezzo** [comment]
@vepain It seems to stop randomly (always during album indexing, but not always at the same moment). What's strange is that all crashes during indexing are being caught and logged (at least that's how the code looks like it should behave). Because it's not being logged in your case, I'm starting to wonder if an external problem is causing the crash. Could you have a look in the Ubuntu log file at /var/log/messages if there is a message concerning the crash?

**Comment by vepain** [comment]
Mmm, I wan not able to find ubuntu log messages, I will continue to investigate in this direction.

However, I launched Dopamine in the terminal, and it provides a final error message:
```sh
❯ dopamine
22:35:47.098 › [Main] [Main] +++ Starting +++
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
22:35:50.015 › [Indexer] [indexCollectionIfOutdatedAsync] Indexing collection.
22:35:52.418 › [CollectionChecker] [isCollectionOutdatedAsync] Collection is up to date
22:35:52.419 › [Indexer] [indexCollectionIfOutdatedAsync] Collection is not outdated.
22:35:52.419 › [AlbumArtworkIndexer] [indexAlbumArtworkAsync] +++ STARTED INDEXING ALBUM ARTWORK +++
22:35:52.430 › [AlbumArtworkRemover] [removeAlbumArtworkThatHasNoTrackAsync] There is no album artwork to remove. Time required: 10 ms.
22:35:52.440 › [AlbumArtworkRemover] [removeAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] There is no album artwork to remove. Time required: 10 ms.
22:35:52.441 › [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Adding album artwork for albumKeyIndex: ''
22:35:52.461 › [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Found 611 album data that needs indexing
22:35:52.482 › [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 1 album artwork
22:35:58.745 › [AlbumArtworkAdder] [addAlbumArtworkForTracksThatNeedAlbumArtworkIndexingAsync] Added 59 album artwork

***MEMORY-ERROR***: dopamine[104812]: GSlice: assertion failed: sinfo->n_allocated > 0
fish: Job 1, 'dopamine' terminated by signal SIGABRT (Abandon)
```

**Comment by vepain** [comment]
Note that I can fix temporarily it by relaunch several time the Dopamine: the caches are used and are completed each time until all the artworks are indexed.

**Comment by digimezzo** [comment]
@vepain Thanks for launching via terminal. That memory error is very interesting. It might be caused by how I'm using the "Sharp" library to resize album art. I'm pasting some links related to this issue below so I can further investigate:

https://github.com/electron/electron/issues/38048
https://github.com/lovell/sharp/issues/3817

**Comment by digimezzo** [comment]
@vepain I've created a new release containing a possible fix for that crash. Could you test it out? It's here: https://github.com/digimezzo/dopamine/releases/tag/v3.0.0-preview.28-ubuntu-crash-fix

**Comment by vepain** [comment]
@digimezzo Thank you for this hotfix.
I cannot run this new version of Dopamine:
```sh
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not load the "sharp" module using the linux-x64 runtime
ERR_DLOPEN_FAILED: libvips-cpp.so.42: Ne peut ouvrir le fichier d'objet partagÃ©: Aucun fichier ou dossier de ce nom
Possible solutions:
- Please upgrade Node.js:
    Found 18.15.0
    Requires ^18.17.0 || ^20.3.0 || >=21.0.0
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/opt/Dopamine/resources/app.asar/node_modules/sharp/lib/sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/Dopamine/resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

**Comment by digimezzo** [comment]
@vepain Thank you for testing it out. I understand what's wrong, but will need some time to fix it. I'll make a new release as soon as I figured it out.

**Comment by vepain** [comment]
@digimezzo Thank you a lot, sorry for answering you during the week-end, take time and rest!

**Comment by digimezzo** [comment]
@vepain Don't worry. I love doing this. I know what's wrong, but solving it will be a challenge. I'll work on it in the next few days.

**Comment by digimezzo** [comment]
@vepain I've updated the release at this link: https://github.com/digimezzo/dopamine/releases/tag/v3.0.0-preview.28-ubuntu-crash-fix

It should fix your issue. Could you try it out and let me know how it goes? Thank you.

**Comment by vepain** [comment]
@digimezzo Thank you, it works!

The test I did: 
- unmount the disk where I store my music
- let dopamine cleaning the index (note that dopamine needed to be re-lauchn to fully remove the album from the view list)
- upgrade dopamine
- mount the disk
- launch dopamine, here the logs:
```sh
❯ dopamine
10:21:58.588 › [Main] [Main] +++ Starting +++
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
10:22:01.412 › [Indexer] [indexCollectionIfOutdatedAsync] Indexing collection.
[11385:0801/102210.314266:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[11385:0801/102212.317219:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[11385:0801/102213.319350:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
10:22:42.414 › [CollectionChecker] [isCollectionOutdatedAsync] Collection is outdated: tracksNeedIndexing=false, numberOfTracksHasChanged=true, lastDateModifiedHasChanged=true
10:22:42.414 › [Indexer] [indexCollectionIfOutdatedAsync] Collection is outdated.
10:22:42.415 › [TrackIndexer] [indexTracksAsync] +++ STARTED INDEXING TRACKS +++
10:22:42.415 › [TrackRemover] [removeTracksThatDoNoNotBelongToFoldersAsync] There are no tracks to remove. Time required: 0 ms
10:22:42.416 › [TrackRemover] [removeTracksThatAreNotFoundOnDiskAsync] Found 0 tracks.
10:22:42.416 › [TrackRemover] [removeTracksThatAreNotFoundOnDiskAsync] Removed 0 tracks. Time required: 0 ms
10:22:42.417 › [TrackRemover] [removeFolderTracksForInexistingTracksAsync] There are no folder tracks to remove. Time required: 0 ms
10:22:42.417 › [TrackUpdater] [updateTracksThatAreOutOfDateAsync] Updated tracks: 0. Time required: 0 ms
10:22:44.586 › [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 1 tracks
10:24:15.582 › [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 2209 tracks
10:25:28.428 › [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 4475 tracks
10:26:49.312 › [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 6741 tracks
10:27:59.253 › [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 9006 tracks
10:29:34.741 › [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Processed 11272 tracks
10:29:36.596 › [TrackAdder] [addTracksThatAreNotInTheDatabaseAsync] Added tracks: 11328. Time required: 414178 ms
10:29:36.597 › [TrackIndexer] [indexTracksAsync] +++ FINISHED INDEXING TRACKS (Time required: 414182 ms) +++
```

**Comment by digimezzo** [comment]
@vepain Excellent! Thank you for the extensive test.
